// packages/create-neptune/templates/vue/src/Dashboard.vue
<script setup lang="ts">
import type { ModeOption } from "@neptune.fintech/vue-ui";

defineProps<{ mode: ModeOption }>();
defineEmits<{ (e: "toggle-mode"): void }>();

function sendMoney() {
  window.alert("Wire this button to your transfer flow.");
}
</script>

<template>
  <div class="app">
    <header class="app__bar">
      <span class="app__brand">{{PROJECT_TITLE}}</span>
      <button class="app__mode" type="button" @click="$emit('toggle-mode')">
        {{ mode === "dark" ? "☀ Light" : "☾ Dark" }}
      </button>
    </header>

    <main class="app__body">
      <npt-balance-card
        hero
        label="Available balance"
        amount="12,480.50"
        currency="LYD"
        account="•••• 4821"
      ></npt-balance-card>

      <div class="stat-row">
        <npt-stat-card label="Income" value="9,120" unit="LYD" delta="+8.2%"></npt-stat-card>
        <npt-stat-card label="Spending" value="3,540" unit="LYD" delta="-2.1%"></npt-stat-card>
      </div>

      <npt-quick-actions>
        <npt-quick-action label="Send"><npt-icon slot="icon" name="transfer"></npt-icon></npt-quick-action>
        <npt-quick-action label="Request"><npt-icon slot="icon" name="wallet"></npt-icon></npt-quick-action>
        <npt-quick-action label="Pay"><npt-icon slot="icon" name="card"></npt-icon></npt-quick-action>
        <npt-quick-action label="Top up"><npt-icon slot="icon" name="card-add"></npt-icon></npt-quick-action>
      </npt-quick-actions>

      <p class="section-title">Recent activity</p>
      <npt-card variant="outlined" class="txns">
        <npt-transaction-row title="Salary" subtitle="Today · Transfer" amount="+3,200.00" currency="LYD" credit></npt-transaction-row>
        <npt-transaction-row title="Grocery Market" subtitle="Yesterday · Card" amount="-86.40" currency="LYD"></npt-transaction-row>
        <npt-transaction-row title="Electricity" subtitle="Mon · Bill" amount="-120.00" currency="LYD"></npt-transaction-row>
        <npt-transaction-row title="Refund" subtitle="Sun · OnePay" amount="+45.00" currency="LYD" credit></npt-transaction-row>
      </npt-card>

      <npt-button variant="filled" @click="sendMoney">Send money</npt-button>
    </main>

    <nav class="app__nav">
      <npt-nav-bar>
        <npt-nav-item label="Home" active><npt-icon name="home"></npt-icon></npt-nav-item>
        <npt-nav-item label="Cards"><npt-icon name="card"></npt-icon></npt-nav-item>
        <npt-nav-item label="Pay"><npt-icon name="transfer"></npt-icon></npt-nav-item>
        <npt-nav-item label="More"><npt-icon name="settings"></npt-icon></npt-nav-item>
      </npt-nav-bar>
    </nav>
  </div>
</template>

// packages/create-neptune/templates/react-native/src/Dashboard.tsx
// {{PROJECT_TITLE}} — sample dashboard, composed from @neptune.fintech/react-native-ui.
import { Pressable, SafeAreaView, ScrollView, StyleSheet, View } from "react-native";
import {
  NeptuneBalanceCard,
  NeptuneButton,
  NeptuneCard,
  NeptuneText,
  NeptuneTransactionRow,
  useNeptuneTheme,
} from "@neptune.fintech/react-native-ui";
import type { Mode } from "@neptune.fintech/react-native-ui";

export interface DashboardProps {
  mode: Mode;
  onToggleMode: () => void;
}

export function Dashboard({ mode, onToggleMode }: DashboardProps) {
  const theme = useNeptuneTheme();
  const c = theme.colors;

  return (
    <SafeAreaView style={[styles.root, { backgroundColor: c.background }]}>
      <View style={styles.bar}>
        <NeptuneText variant="title">{{PROJECT_TITLE}}</NeptuneText>
        <Pressable
          onPress={onToggleMode}
          style={[styles.modeBtn, { borderColor: c["outline-variant"] }]}
        >
          <NeptuneText variant="label">{mode === "dark" ? "☀ Light" : "☾ Dark"}</NeptuneText>
        </Pressable>
      </View>

      <ScrollView contentContainerStyle={styles.body}>
        <NeptuneBalanceCard label="Available balance" amount="12,480.50" currency="LYD" />

        <View style={styles.statRow}>
          <NeptuneCard container style={styles.stat}>
            <NeptuneText variant="label" muted>
              Income
            </NeptuneText>
            <NeptuneText variant="title">9,120 LYD</NeptuneText>
          </NeptuneCard>
          <NeptuneCard container style={styles.stat}>
            <NeptuneText variant="label" muted>
              Spending
            </NeptuneText>
            <NeptuneText variant="title">3,540 LYD</NeptuneText>
          </NeptuneCard>
        </View>

        <NeptuneText variant="label" muted style={styles.sectionTitle}>
          RECENT ACTIVITY
        </NeptuneText>
        <NeptuneCard outlined>
          <NeptuneTransactionRow title="Salary" subtitle="Today · Transfer" amount="+3,200.00 LYD" credit />
          <NeptuneTransactionRow title="Grocery Market" subtitle="Yesterday · Card" amount="-86.40 LYD" />
          <NeptuneTransactionRow title="Electricity" subtitle="Mon · Bill" amount="-120.00 LYD" />
          <NeptuneTransactionRow title="Refund" subtitle="Sun · OnePay" amount="+45.00 LYD" credit />
        </NeptuneCard>

        <NeptuneButton variant="filled" label="Send money" onPress={() => undefined} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  bar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  modeBtn: { borderWidth: 1, borderRadius: 999, paddingVertical: 8, paddingHorizontal: 14 },
  body: { padding: 20, gap: 16 },
  statRow: { flexDirection: "row", gap: 12 },
  stat: { flex: 1, gap: 4 },
  sectionTitle: { marginTop: 4, letterSpacing: 1 },
});
