// packages/create-neptune/templates/vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { NeptuneProvider } from "@neptune.fintech/vue-ui";
import type { ModeOption } from "@neptune.fintech/vue-ui";

import Dashboard from "./Dashboard.vue";

const mode = ref<ModeOption>("{{MODE}}");
function toggleMode() {
  mode.value = mode.value === "dark" ? "light" : "dark";
}
</script>

<template>
  <NeptuneProvider theme="{{BRAND}}" :mode="mode" dir="{{DIR}}">
    <Dashboard :mode="mode" @toggle-mode="toggleMode" />
  </NeptuneProvider>
</template>

// packages/create-neptune/templates/react-native/App.tsx
// {{PROJECT_TITLE}} — Neptune Odyssey starter (React Native / Expo).
import { useState } from "react";
import { StatusBar } from "expo-status-bar";
import { NeptuneProvider } from "@neptune.fintech/react-native-ui";
import type { Mode } from "@neptune.fintech/react-native-ui";

import { Dashboard } from "./src/Dashboard";

export default function App() {
  const [mode, setMode] = useState<Mode>("{{MODE}}");
  const toggleMode = () => setMode((m) => (m === "dark" ? "light" : "dark"));

  return (
    <NeptuneProvider input="{{BRAND}}" mode={mode} dir="{{DIR}}">
      <Dashboard mode={mode} onToggleMode={toggleMode} />
      <StatusBar style={mode === "dark" ? "light" : "dark"} />
    </NeptuneProvider>
  );
}
