// packages/create-neptune/templates/vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { NeptuneProvider } from "@neptune.fintech/vue-ui";
import type { ModeOption } from "@neptune.fintech/vue-ui";

import Dashboard from "./Dashboard.vue";

const mode = ref<ModeOption>("{{MODE}}");
function toggleMode() {
  mode.value = mode.value === "dark" ? "light" : "dark";
}
</script>

<template>
  <NeptuneProvider theme="{{BRAND}}" :mode="mode" dir="{{DIR}}">
    <Dashboard :mode="mode" @toggle-mode="toggleMode" />
  </NeptuneProvider>
</template>

// packages/create-neptune/templates/react/src/App.tsx
import { useState } from "react";
import { NeptuneProvider } from "@neptune.fintech/react-ui";
import type { ModeOption } from "@neptune.fintech/react-ui";

import { Dashboard } from "./Dashboard";

export function App() {
  const [mode, setMode] = useState<ModeOption>("{{MODE}}");
  const toggleMode = () => setMode((m) => (m === "dark" ? "light" : "dark"));

  return (
    <NeptuneProvider theme="{{BRAND}}" mode={mode} dir="{{DIR}}">
      <Dashboard mode={mode} onToggleMode={toggleMode} />
    </NeptuneProvider>
  );
}
