// packages/create-neptune/templates/vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { NeptuneProvider } from "@neptune.fintech/vue-ui";
import type { ModeOption } from "@neptune.fintech/vue-ui";

import Dashboard from "./Dashboard.vue";

const mode = ref<ModeOption>("{{MODE}}");
function toggleMode() {
  mode.value = mode.value === "dark" ? "light" : "dark";
}
</script>

<template>
  <NeptuneProvider theme="{{BRAND}}" :mode="mode" dir="{{DIR}}">
    <Dashboard :mode="mode" @toggle-mode="toggleMode" />
  </NeptuneProvider>
</template>

// packages/create-neptune/templates/svelte/src/App.svelte
<script lang="ts">
  import { theme } from "@neptune.fintech/svelte-ui";
  import type { ModeOption } from "@neptune.fintech/svelte-ui";
  import Dashboard from "./Dashboard.svelte";

  let mode: ModeOption = $state("{{MODE}}");
  function toggleMode() {
    mode = mode === "dark" ? "light" : "dark";
  }
</script>

<div class="neptune-provider" use:theme={{ input: "{{BRAND}}", mode, dir: "{{DIR}}" }}>
  <Dashboard {mode} {toggleMode} />
</div>
